version: '3'

services:
  flask-socketio-load-balancing-redis:
    image: redis:latest
    container_name: flask-socketio-load-balancing-redis
    restart: always
    ports:
      - "6379"
        
  api:
    build:
      context: .
    depends_on:
      - flask-socketio-load-balancing-redis
    ports:
      - "5003"

  flask-socketio-load-balancing-nginx:
    image: nginx:latest
    container_name: flask-socketio-load-balancing-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      - api
    ports:
      - "5003:5003"